services:
  # Dịch vụ MinIO
  - type: web
    name: thesis-guard-minio
    env: docker
    dockerfilePath: ./Dockerfile.minio
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false
    disk:
      name: minio-data
      mountPath: /mnt/data
      sizeGB: 10
    # Sử dụng lệnh khởi động giống local của bạn
    dockerCommand: "minio server /mnt/data --console-address \":9001\""
    # Chỉ định cổng cho Render
    port: 9000
    # Cấu hình health check
    healthCheckPath: /minio/health/live