services:
  # Dịch vụ MinIO
  - type: web
    name: thesis-guard-minio
    env: docker
    dockerfilePath: ./Dockerfile.minio
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 10
    # Chỉ định lệnh khởi động đúng
    dockerCommand: "minio server --address :9000 --console-address :9001 /data"
    # Chỉ định cổng cho Render
    port: 9000
    # Cấu hình health check
    healthCheckPath: /minio/health/live